var qfilename = new Array();
var ix = 0;
qfilename[ix] = "stakeholder-capitalism.html";
ix++;
qfilename[ix] = "fuzzy-concept.html";
ix++;
qfilename[ix] = "i-must-study-politics-and-war.html";
ix++;
qfilename[ix] = "a-dark-procession.html";
ix++;
qfilename[ix] = "merely-thoroughly-outrageous.html";
ix++;
qfilename[ix] = "occasions-when-the-intellect-retires-gracefully.html";
ix++;
qfilename[ix] = "the-only-sign-of-mental-activity.html";
ix++;
qfilename[ix] = "we-dont-even-own-suits.html";
ix++;
qfilename[ix] = "model-ii-decision-making.html";
ix++;
qfilename[ix] = "model-ii-values.html";
ix++;
qfilename[ix] = "a-beast-or-a-god.html";
ix++;
qfilename[ix] = "entertain-a-thought.html";
ix++;
qfilename[ix] = "the-four-fold-way.html";
ix++;
qfilename[ix] = "the-cult-of-ignorance.html";
ix++;
qfilename[ix] = "the-only-sensible-procedure-for-a-critic.html";
ix++;
qfilename[ix] = "cockpits-with-instruments-controlled-by-gremlins.html";
ix++;
qfilename[ix] = "we-need-a-place-to-stand.html";
ix++;
qfilename[ix] = "careful-thoughtful-small-practical-efforts.html";
ix++;
qfilename[ix] = "thinking-should-be-generous-and-have-a-good-appetite.html";
ix++;
qfilename[ix] = "an-emotional-poverty-so-bottomless.html";
ix++;
qfilename[ix] = "any-love-for-justice.html";
ix++;
qfilename[ix] = "ancient-ethnic-sores-belching-fire.html";
ix++;
qfilename[ix] = "hands-that-must-work.html";
ix++;
qfilename[ix] = "our-reply-to-violence.html";
ix++;
qfilename[ix] = "seeing-the-bigger-picture-from-multiple-angles.html";
ix++;
qfilename[ix] = "art-science-and-empire.html";
ix++;
qfilename[ix] = "expectations-of-holiness.html";
ix++;
qfilename[ix] = "minute-particulars.html";
ix++;
qfilename[ix] = "to-see-a-world-in-a-grain-of-sand.html";
ix++;
qfilename[ix] = "cost-of-education.html";
ix++;
qfilename[ix] = "capitalists-who-worship-only-at-the-feet-of-capitalism.html";
ix++;
qfilename[ix] = "having-fewer-children-and-grandchildren.html";
ix++;
qfilename[ix] = "the-tautness-of-this-resonant-connection.html";
ix++;
qfilename[ix] = "chaos-and-mediocrity.html";
ix++;
qfilename[ix] = "counter-cultures-own-values-and-aesthetics-decayed.html";
ix++;
qfilename[ix] = "history-as-postmodern-collage.html";
ix++;
qfilename[ix] = "little-i-recognized-as-music.html";
ix++;
qfilename[ix] = "never-knew-cocaine-to-improve-anything.html";
ix++;
qfilename[ix] = "records-we-made-together-in-the-sixties.html";
ix++;
qfilename[ix] = "sixties-surpluses-of-money-and-time.html";
ix++;
qfilename[ix] = "people-ask-me-to-predict-the-future.html";
ix++;
qfilename[ix] = "television-mesmerizes-people.html";
ix++;
qfilename[ix] = "art-is-a-hammer.html";
ix++;
qfilename[ix] = "all-of-us-are-trim-tabs.html";
ix++;
qfilename[ix] = "you-are-going-to-have-to-make-it-different.html";
ix++;
qfilename[ix] = "life-is-a-series-of-daring-adventures-from-a-secure-base.html";
ix++;
qfilename[ix] = "life-is-more-like-settling-a-sequence-of-villages.html";
ix++;
qfilename[ix] = "a-diminishing-sense-of-shared-humanity.html";
ix++;
qfilename[ix] = "nirvana-antipattern.html";
ix++;
qfilename[ix] = "two-ideas-of-government.html";
ix++;
qfilename[ix] = "between-saturday-night-and-sunday-morning.html";
ix++;
qfilename[ix] = "its-the-rich-class-thats-winning.html";
ix++;
qfilename[ix] = "excitement-from-art.html";
ix++;
qfilename[ix] = "an-invincible-summer.html";
ix++;
qfilename[ix] = "work-soul-and-life.html";
ix++;
qfilename[ix] = "to-end-up-here-in-a-pile-of-bones.html";
ix++;
qfilename[ix] = "moral-sawdust.html";
ix++;
qfilename[ix] = "six-impossible-things-before-breakfast.html";
ix++;
qfilename[ix] = "a-mind-is-blown.html";
ix++;
qfilename[ix] = "down-these-mean-streets.html";
ix++;
qfilename[ix] = "ill-take-the-big-sordid-dirty-crooked-city.html";
ix++;
qfilename[ix] = "vital-and-significant-forms-of-art.html";
ix++;
qfilename[ix] = "conservatives-and-progressives.html";
ix++;
qfilename[ix] = "generosity-among-the-rich.html";
ix++;
qfilename[ix] = "mysticism-has-kept-men-sane.html";
ix++;
qfilename[ix] = "taking-a-fence-down.html";
ix++;
qfilename[ix] = "the-cause-which-is-blocking-all-progress.html";
ix++;
qfilename[ix] = "the-center-of-every-mans-existence-is-a-dream.html";
ix++;
qfilename[ix] = "the-difference-between-construction-and-creation.html";
ix++;
qfilename[ix] = "this-dazed-and-dramatic-ignorance.html";
ix++;
qfilename[ix] = "we-are-in-eden-still.html";
ix++;
qfilename[ix] = "symbolic-language.html";
ix++;
qfilename[ix] = "democracy-is-worst-form-of-government.html";
ix++;
qfilename[ix] = "liberalism-is-not-socialism.html";
ix++;
qfilename[ix] = "we-are-doing-our-best.html";
ix++;
qfilename[ix] = "rough-consensus-and-running-code.html";
ix++;
qfilename[ix] = "deeper-convictions-of-the-heart.html";
ix++;
qfilename[ix] = "all-must-be-held-valuable-or-none.html";
ix++;
qfilename[ix] = "the-divine-gift-of-purely-nonsensical-speech-and-action.html";
ix++;
qfilename[ix] = "evolutionary-drive-towards-complexity.html";
ix++;
qfilename[ix] = "belief-in-impossible-things.html";
ix++;
qfilename[ix] = "wonderment-is-the-first-passion-of-all.html";
ix++;
qfilename[ix] = "thnk-globally-act-locally.html";
ix++;
qfilename[ix] = "a-happy-man.html";
ix++;
qfilename[ix] = "a-man-of-value.html";
ix++;
qfilename[ix] = "moral-religion.html";
ix++;
qfilename[ix] = "only-a-human-being.html";
ix++;
qfilename[ix] = "simplicity-and-complexity.html";
ix++;
qfilename[ix] = "the-mysterious.html";
ix++;
qfilename[ix] = "the-supreme-goal-of-all-theory.html";
ix++;
qfilename[ix] = "this-highest-kind-of-religious-feeling.html";
ix++;
qfilename[ix] = "to-give-in-the-same-measure.html";
ix++;
qfilename[ix] = "violent-opposition-from-mediocre-minds.html";
ix++;
qfilename[ix] = "a-foolish-consistency.html";
ix++;
qfilename[ix] = "the-time-worn-yoke-of-their-opinions.html";
ix++;
qfilename[ix] = "when-i-get-a-little-money-i-buy-books.html";
ix++;
qfilename[ix] = "a-first-rate-intelligence.html";
ix++;
qfilename[ix] = "faster-horses.html";
ix++;
qfilename[ix] = "only-connect.html";
ix++;
qfilename[ix] = "the-rainbow-bridge.html";
ix++;
qfilename[ix] = "wriggling.html";
ix++;
qfilename[ix] = "couldnt-everyones-life-become-a-work-of-art.html";
ix++;
qfilename[ix] = "push-outward.html";
ix++;
qfilename[ix] = "each-man-is-questioned-by-life.html";
ix++;
qfilename[ix] = "love-is-the-ultimate-and-the-highest-goal.html";
ix++;
qfilename[ix] = "every-body-cries-a-union-is-absolutely-necessary.html";
ix++;
qfilename[ix] = "by-gifts-one-makes-slaves.html";
ix++;
qfilename[ix] = "the-stagnation-of-american-middle-class-living-standards.html";
ix++;
qfilename[ix] = "conventional-views.html";
ix++;
qfilename[ix] = "a-working-simple-system.html";
ix++;
qfilename[ix] = "prime-training-for-permanent-underclasses.html";
ix++;
qfilename[ix] = "egocentric-existence.html";
ix++;
qfilename[ix] = "mans-nature-is-an-open-constantly-evolving-system.html";
ix++;
qfilename[ix] = "while-he-was-focusing-on-the-inner-self-his-outer-world-has-gone-to-pot.html";
ix++;
qfilename[ix] = "climate-changers.html";
ix++;
qfilename[ix] = "imagination-is-not-a-means-of-making-money.html";
ix++;
qfilename[ix] = "successful-planning.html";
ix++;
qfilename[ix] = "thinkings-a-dizzy-business.html";
ix++;
qfilename[ix] = "a-completely-free-market.html";
ix++;
qfilename[ix] = "a-meaningful-life.html";
ix++;
qfilename[ix] = "authentic-cultures.html";
ix++;
qfilename[ix] = "consistency-is-the-playground-of-dull-minds.html";
ix++;
qfilename[ix] = "cultures-as-a-kind-of-mental-infection.html";
ix++;
qfilename[ix] = "economic-growth-will-not-save-the-global-ecosystem.html";
ix++;
qfilename[ix] = "evolutionary-success-and-individual-suffering.html";
ix++;
qfilename[ix] = "fear-of-missing-out.html";
ix++;
qfilename[ix] = "flexible-cooperation-with-strangers.html";
ix++;
qfilename[ix] = "from-a-biological-perspective-nothing-is-unnatural.html";
ix++;
qfilename[ix] = "history-is-something-very-few-people-have-been-doing.html";
ix++;
qfilename[ix] = "human-imagination-more-than-biological-reality.html";
ix++;
qfilename[ix] = "if-the-future-of-humanity-is-decided-in-your-absence....html";
ix++;
qfilename[ix] = "most-sociopolitical-hierarchies-lack-a-logical-or-biological-basis.html";
ix++;
qfilename[ix] = "myths-are-stronger-than-anyone-could-have-imagined.html";
ix++;
qfilename[ix] = "no-single-natural-way-of-life-for-sapiens.html";
ix++;
qfilename[ix] = "our-social-order-now-in-a-state-of-permanent-flux.html";
ix++;
qfilename[ix] = "people-are-happy-to-give-away-their-most-valuable-asset.html";
ix++;
qfilename[ix] = "regulating-the-ownership-of-data.html";
ix++;
qfilename[ix] = "struggling-against-irrelevance.html";
ix++;
qfilename[ix] = "the-awesome-power-of-culture.html";
ix++;
qfilename[ix] = "the-world-empire-enforces-world-peace.html";
ix++;
qfilename[ix] = "the-brightest-goat-in-the-herd.html";
ix++;
qfilename[ix] = "the-system-has-been-shaping-and-reshaping-our-minds.html";
ix++;
qfilename[ix] = "these-principles-have-no-objective-validity.html";
ix++;
qfilename[ix] = "trust-in-the-future.html";
ix++;
qfilename[ix] = "unprecedented-growth-in-human-power.html";
ix++;
qfilename[ix] = "when-growth-becomes-a-supreme-good.html";
ix++;
qfilename[ix] = "why-study-history.html";
ix++;
qfilename[ix] = "the-change-dilemma.html";
ix++;
qfilename[ix] = "daily-acts-of-trivia.html";
ix++;
qfilename[ix] = "the-other-side-of-complexity.html";
ix++;
qfilename[ix] = "the-inner-life-of-the-artist.html";
ix++;
qfilename[ix] = "torturing-the-data.html";
ix++;
qfilename[ix] = "merely-a-muddle.html";
ix++;
qfilename[ix] = "ignorant-and-free.html";
ix++;
qfilename[ix] = "unintelligible-propositions.html";
ix++;
qfilename[ix] = "little-things-seen-largely.html";
ix++;
qfilename[ix] = "thou-shalt-love-thy-neighbour-as-thyself.html";
ix++;
qfilename[ix] = "a-bicycle-for-our-minds.html";
ix++;
qfilename[ix] = "good-management-is-like-the-beatles.html";
ix++;
qfilename[ix] = "life-can-be-much-broader.html";
ix++;
qfilename[ix] = "people-with-passion.html";
ix++;
qfilename[ix] = "selling-sugared-water.html";
ix++;
qfilename[ix] = "technology-married-with-the-humanities.html";
ix++;
qfilename[ix] = "the-underlying-principle-of-the-problem.html";
ix++;
qfilename[ix] = "the-axis-is-constructive-destructive.html";
ix++;
qfilename[ix] = "we-have-wonderful-arguments.html";
ix++;
qfilename[ix] = "where-the-puck-is-going-to-be.html";
ix++;
qfilename[ix] = "steve-jobs-ideals.html";
ix++;
qfilename[ix] = "this-strange-hankering-for-play-and-surprise.html";
ix++;
qfilename[ix] = "facts-are-facts.html";
ix++;
qfilename[ix] = "the-point-of-modern-propaganda.html";
ix++;
qfilename[ix] = "the-best-way-to-predict-the-future-is-to-invent-it.html";
ix++;
qfilename[ix] = "the-fragile-constructs-of-history.html";
ix++;
qfilename[ix] = "when-you-can-measure-what-you-are-speaking-about.html";
ix++;
qfilename[ix] = "the-extent-of-freedom-in-all-of-its-dimensions.html";
ix++;
qfilename[ix] = "defending-the-pursuit-of-learning.html";
ix++;
qfilename[ix] = "let-us-accept-our-own-responsibility-for-the-future.html";
ix++;
qfilename[ix] = "national-parks-and-reserves.html";
ix++;
qfilename[ix] = "our-privileges-can-be-no-greater-than-our-obligations.html";
ix++;
qfilename[ix] = "the-discomfort-of-thought.html";
ix++;
qfilename[ix] = "the-golden-eternity.html";
ix++;
qfilename[ix] = "civilization-was-a-thin-and-precarious-crust.html";
ix++;
qfilename[ix] = "technological-unemployment.html";
ix++;
qfilename[ix] = "to-live-wisely-and-agreeably-and-well.html";
ix++;
qfilename[ix] = "an-edifice-which-produces-beggars-needs-restructuring.html";
ix++;
qfilename[ix] = "an-ordinary-person-doing-an-ordinary-job.html";
ix++;
qfilename[ix] = "creatively-maladjusted.html";
ix++;
qfilename[ix] = "ends-for-which-we-live.html";
ix++;
qfilename[ix] = "guided-missiles-and-misguided-men.html";
ix++;
qfilename[ix] = "intelligence-plus-character.html";
ix++;
qfilename[ix] = "intelligent-guides-of-family-planning.html";
ix++;
qfilename[ix] = "single-garment-of-destiny.html";
ix++;
qfilename[ix] = "ten-thousand-fools-proclaim-themselves.html";
ix++;
qfilename[ix] = "the-arc-of-history.html";
ix++;
qfilename[ix] = "to-save-man-from-the-morass-of-propaganda.html";
ix++;
qfilename[ix] = "unarmed-truth-and-unconditional-love.html";
ix++;
qfilename[ix] = "when-machines-are-considered-more-important-than-people.html";
ix++;
qfilename[ix] = "you-have-your-position-because-of-the-events-of-history.html";
ix++;
qfilename[ix] = "the-biological-evolution-of-homo-sapiens-was-usurped-by-socio-cultural-evolution.html";
ix++;
qfilename[ix] = "critical-thinking-followed-by-action.html";
ix++;
qfilename[ix] = "we-should-always-be-fighting-evil.html";
ix++;
qfilename[ix] = "equals.html";
ix++;
qfilename[ix] = "more-popular-than-jesus.html";
ix++;
qfilename[ix] = "the-enormous-extension-of-our-being.html";
ix++;
qfilename[ix] = "we-are-idealists-and-we-are-realists.html";
ix++;
qfilename[ix] = "discoveries-and-inventions.html";
ix++;
qfilename[ix] = "labor-is-the-superior-of-capital.html";
ix++;
qfilename[ix] = "the-better-angels-of-our-nature.html";
ix++;
qfilename[ix] = "the-legitimate-object-of-government.html";
ix++;
qfilename[ix] = "a-hereditary-meritocracy.html";
ix++;
qfilename[ix] = "capitalism-works-best-in-societies-where-there-are-high-levels-of-trust.html";
ix++;
qfilename[ix] = "conscious-improvement-for-the-masses.html";
ix++;
qfilename[ix] = "governments-losing-their-ability-to-anticipate-events.html";
ix++;
qfilename[ix] = "history-is-not-some-self-driving-car.html";
ix++;
qfilename[ix] = "liberal-democracys-strongest-glue-is-economic-growth.html";
ix++;
qfilename[ix] = "responsible-nationalism.html";
ix++;
qfilename[ix] = "the-yen-to-work-drops-in-flat-economies.html";
ix++;
qfilename[ix] = "what-would-a-new-social-compact-look-like.html";
ix++;
qfilename[ix] = "writing-off-half-of-society-as-deplorable.html";
ix++;
qfilename[ix] = "introduction-of-a-new-order-of-things.html";
ix++;
qfilename[ix] = "living-happily-ever-after.html";
ix++;
qfilename[ix] = "balance-is-required-to-maintain-democracy.html";
ix++;
qfilename[ix] = "inextricably-linked-in-freedom.html";
ix++;
qfilename[ix] = "integrity-and-conviction.html";
ix++;
qfilename[ix] = "the-challenge-of-swing.html";
ix++;
qfilename[ix] = "the-love-of-what-we-are-doing.html";
ix++;
qfilename[ix] = "the-philosophy-of-jazz.html";
ix++;
qfilename[ix] = "the-power-of-art.html";
ix++;
qfilename[ix] = "the-undisputed-sovereignty-of-the-human-being.html";
ix++;
qfilename[ix] = "a-book-is-a-mans-best-friend.html";
ix++;
qfilename[ix] = "the-original-naivet.html";
ix++;
qfilename[ix] = "it-is-foolish-to-view-realism-and-idealism-as-incompatible.html";
ix++;
qfilename[ix] = "the-ultimate-democracy.html";
ix++;
qfilename[ix] = "changing-the-world.html";
ix++;
qfilename[ix] = "quality-of-children-vs.-quantity.html";
ix++;
qfilename[ix] = "easy-solutions.html";
ix++;
qfilename[ix] = "every-third-american.html";
ix++;
qfilename[ix] = "we-must-respect-the-other-fellows-religion.html";
ix++;
qfilename[ix] = "intellectual-debate.html";
ix++;
qfilename[ix] = "enemies-of-art-and-artist.html";
ix++;
qfilename[ix] = "this-dear-fucked-up-planet.html";
ix++;
qfilename[ix] = "we-all-derive-from-the-same-source.html";
ix++;
qfilename[ix] = "if-triangles-had-a-god.html";
ix++;
qfilename[ix] = "a-world-that-is-tolerable.html";
ix++;
qfilename[ix] = "this-faith-in-consciousness.html";
ix++;
qfilename[ix] = "thralls-to-group-instincts.html";
ix++;
qfilename[ix] = "everyone-is-entitled-to-his-own-opinion-but-not-his-own-facts.html";
ix++;
qfilename[ix] = "living-with-the-strains-of-complexity.html";
ix++;
qfilename[ix] = "that-community-asks-for-and-gets-chaos.html";
ix++;
qfilename[ix] = "the-institution-of-the-family.html";
ix++;
qfilename[ix] = "quality-matters.html";
ix++;
qfilename[ix] = "hard-discipline-of-reasonableness-and-honesty.html";
ix++;
qfilename[ix] = "first-they-came....html";
ix++;
qfilename[ix] = "generosity-is-the-robust-strategy.html";
ix++;
qfilename[ix] = "governance-is-essential.html";
ix++;
qfilename[ix] = "in-the-thrall-of-a-vast-world-spanning-machine.html";
ix++;
qfilename[ix] = "worshipping-the-divine-right-of-capital.html";
ix++;
qfilename[ix] = "a-return-to-these-truths.html";
ix++;
qfilename[ix] = "the-makers-of-things.html";
ix++;
qfilename[ix] = "no-person-in-america-should-be-too-poor-to-live.html";
ix++;
qfilename[ix] = "the-third-place.html";
ix++;
qfilename[ix] = "politics-and-the-debasement-of-language.html";
ix++;
qfilename[ix] = "accidents-of-birth.html";
ix++;
qfilename[ix] = "independence-freedom-and-opportunity-for-every-member-of-society.html";
ix++;
qfilename[ix] = "nordic-societies-have-simply-taken-the-job-of-government-seriously.html";
ix++;
qfilename[ix] = "the-us-remains-astonishingly-backward-when-it-comes-to-education.html";
ix++;
qfilename[ix] = "you-can-simply-focus-on-raising-a-human-being.html";
ix++;
qfilename[ix] = "the-web-of-life.html";
ix++;
qfilename[ix] = "freedom-of-expression-in-business.html";
ix++;
qfilename[ix] = "diversity-helps-your-business-but-not-the-way-you-think.html";
ix++;
qfilename[ix] = "art-is-a-lie-that-makes-us-realize-truth.html";
ix++;
qfilename[ix] = "a-progressive-annual-tax-on-capital.html";
ix++;
qfilename[ix] = "the-historical-trajectory-of-violence.html";
ix++;
qfilename[ix] = "postels-law.html";
ix++;
qfilename[ix] = "amusing-ourselves-to-death.html";
ix++;
qfilename[ix] = "cultural-as-opposed-to-biological-evolution.html";
ix++;
qfilename[ix] = "investing-in-other-peoples-children.html";
ix++;
qfilename[ix] = "public-truth.html";
ix++;
qfilename[ix] = "public-morality.html";
ix++;
qfilename[ix] = "to-differentiate-truth-from-falsehood.html";
ix++;
qfilename[ix] = "walter-reuther-and-the-ford-robots.html";
ix++;
qfilename[ix] = "ism-mania.html";
ix++;
qfilename[ix] = "people-are-finally-finding-out-that-the-guy-next-door-isnt-a-bad-egg.html";
ix++;
qfilename[ix] = "that-magical-honeycomb-of-words.html";
ix++;
qfilename[ix] = "the-world-is-a-wonderfully-weird-place.html";
ix++;
qfilename[ix] = "i-learned-a-lot-of-things-from-failure.html";
ix++;
qfilename[ix] = "unbelievable-heroes.html";
ix++;
qfilename[ix] = "great-minds-discuss-ideas.html";
ix++;
qfilename[ix] = "discovering-that-i-am-nobody.html";
ix++;
qfilename[ix] = "men-fear-thought.html";
ix++;
qfilename[ix] = "ten-commandments-for-teachers.html";
ix++;
qfilename[ix] = "the-celestial-teapot.html";
ix++;
qfilename[ix] = "bathing-in-mystery-and-confusion.html";
ix++;
qfilename[ix] = "books-are-key-to-understanding-the-world.html";
ix++;
qfilename[ix] = "apes-and-humans.html";
ix++;
qfilename[ix] = "chimps-and-humans.html";
ix++;
qfilename[ix] = "to-prolong-our-presence-on-the-face-of-the-earth.html";
ix++;
qfilename[ix] = "progress-depends-on-retentiveness.html";
ix++;
qfilename[ix] = "only-two-sources-of-real-wealth.html";
ix++;
qfilename[ix] = "small-and-obscure-deeds.html";
ix++;
qfilename[ix] = "learning-from-experience.html";
ix++;
qfilename[ix] = "espn-president-meets-steve-jobs.html";
ix++;
qfilename[ix] = "i-dream-things-that-never-were.html";
ix++;
qfilename[ix] = "progress-depends-on-the-unreasonable-man.html";
ix++;
qfilename[ix] = "when-his-salary-depends-on-his-not-understanding-it.html";
ix++;
qfilename[ix] = "confusion-leads-to-understanding.html";
ix++;
qfilename[ix] = "freedom-of-judgment.html";
ix++;
qfilename[ix] = "notions-to-explain-nature.html";
ix++;
qfilename[ix] = "a-long-conversation.html";
ix++;
qfilename[ix] = "the-trick-in-keeping-bands-together.html";
ix++;
qfilename[ix] = "the-columbia-disaster.html";
ix++;
qfilename[ix] = "the-credibility-of-a-comedian.html";
ix++;
qfilename[ix] = "a-work-ethic-gone-mad.html";
ix++;
qfilename[ix] = "preparing-managers-to-manage.html";
ix++;
qfilename[ix] = "relieving-ignorance.html";
ix++;
qfilename[ix] = "the-exercise-of-the-intellect.html";
ix++;
qfilename[ix] = "the-welfare-of-the-whole-human-race.html";
ix++;
qfilename[ix] = "the-half-finished-heaven.html";
ix++;
qfilename[ix] = "do-the-right-thing.html";
ix++;
qfilename[ix] = "dreams-come-true.html";
ix++;
qfilename[ix] = "capitalism-as-a-market-society.html";
ix++;
qfilename[ix] = "seeking-ways-to-disagree-with-myself.html";
ix++;
qfilename[ix] = "the-opposite-of-popularizing-economics.html";
ix++;
qfilename[ix] = "the-economy-is-too-important-to-leave-to-the-economists.html";
ix++;
qfilename[ix] = "myth-makers.html";
ix++;
qfilename[ix] = "god-and-morality.html";
ix++;
qfilename[ix] = "its-sports-and-its-all-love.html";
ix++;
qfilename[ix] = "monkeys-with-money-and-guns.html";
ix++;
qfilename[ix] = "a-coke-is-a-coke.html";
ix++;
qfilename[ix] = "those-sharp-scratchy-harsh-almost-unpleasant-guys.html";
ix++;
qfilename[ix] = "shareholder-value.html";
ix++;
qfilename[ix] = "the-art-of-progress.html";
ix++;
qfilename[ix] = "the-wonder-remains.html";
ix++;
qfilename[ix] = "set-off-from-the-rest-by-a-line-drawn.html";
ix++;
qfilename[ix] = "the-loftiest-and-purest-art.html";
ix++;
qfilename[ix] = "the-divine-literatus.html";
ix++;
qfilename[ix] = "all-the-worlds-cultures-now-available-to-us.html";
ix++;
qfilename[ix] = "an-integral-god.html";
ix++;
qfilename[ix] = "art-and-spirit.html";
ix++;
qfilename[ix] = "everybody-has-some-important-pieces-of-the-truth.html";
ix++;
qfilename[ix] = "homophobia.html";
ix++;
qfilename[ix] = "levels-of-development.html";
ix++;
qfilename[ix] = "the-beautiful-the-good-and-the-true.html";
ix++;
qfilename[ix] = "the-left-hand-dimension.html";
ix++;
qfilename[ix] = "most-advertising-an-insane-irrelevance.html";
ix++;
qfilename[ix] = "man-must-believe-in-an-open-future.html";
ix++;
qfilename[ix] = "a-planet-sized-problem.html";
ix++;
qfilename[ix] = "the-most-dangerous-of-devotions.html";
ix++;
qfilename[ix] = "the-real-problem-of-humanity.html";
ix++;
qfilename[ix] = "the-toxic-mix-of-religion-and-tribalism.html";
ix++;
qfilename[ix] = "true-character.html";
ix++;
qfilename[ix] = "lean.html";
ix++;
qfilename[ix] = "to-simply-see-human-beings.html";
ix++;
qfilename[ix] = "price-of-success.html";
ix++;
qfilename[ix] = "when-old-men-plant-trees.html";
ix++;
var max = ix;

var now = new Date();
var seed = now.getTime() % 0xffffffff;

function rand(n) {
  seed = (0x015a4e35 * seed) % 0x7fffffff;
  return (seed >> 16) % n;
}

function setContent(n) {
  var thisURL  = document.URL;
  var blogIx   = thisURL.indexOf("/blog/");
  var tagsIx   = thisURL.indexOf("/tags/");
  var quotesIx = thisURL.indexOf("/quotes/");
  var coreIx   = thisURL.indexOf("/core/");
  var introIx  = thisURL.indexOf("/intro/");
  var linksIx  = thisURL.indexOf("/links/");
  var newsIx   = thisURL.indexOf("/news/");
  var page = qfilename[n];
  if (blogIx > 0) {
    page = "../../quotes/" + page;
  }
  else
  if (tagsIx < 0 && quotesIx < 0 && coreIx < 0 && introIx < 0 && linksIx < 0 && newsIx < 0) {
    page = "quotes/" + page;
  } else {
    page = "../quotes/" + page;
  }
  window.location.replace(page);
}

function randomQuote() {
  rq = rand(max);
  if (rq < 0) {
    rq = 0;
  }
  if (rq >= max) {
    rq = max - 1;
  }
  setContent (rq);
}

function firstQuote() {
  var ix = 0;
  setContent(ix);
}

function lastQuote() {
  var ix = max - 1;
  setContent(ix);
}

function nextQuote() {
  bumpQuote(1);
}

function priorQuote() {
  bumpQuote(-1);
}

function bumpQuote(inc) {
  var thisURL = document.URL;
  var lastSlash = thisURL.lastIndexOf("/");
  var thisPage = thisURL.substr(lastSlash + 1);
  var ix = 0;
  var found = false;
  while (ix < max && (! found)) {
    var page = qfilename[ix];
    if (thisPage == page) {
      found = true;
    } else {
      ix++;
    }
  }
  if (found) {
    ix = ix + inc;
    if (ix >= max) {
      ix = 0;
    }
    if (ix < 0) {
      ix = max - 1;
    }
    setContent(ix);
  } else {
    setContent(0);
  }
}
